# Generated by Django 5.0.4 on 2024-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
