# Generated by Django 5.0.4 on 2024-05-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Studio Owner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
