# Generated by Django 5.0.4 on 2024-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_users_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('admin', 'Can view all data'), ('owner', 'Can view owner data only'), ('customer', 'Can view customer data only')),
            },
        ),
    ]
