# Generated by Django 5.0.4 on 2024-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_customuserpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('maximum_daily_capacity', models.IntegerField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('add_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
