# Generated by Django 5.0.4 on 2024-05-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_studios_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserPermissions',
        ),
    ]
