# Generated by Django 5.0.4 on 2024-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_remove_studios_del_stamp_remove_studios_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studios',
            name='maximum_daily_capacity',
            field=models.IntegerField(),
        ),
    ]
