# Generated by Django 5.0.4 on 2024-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_alter_studios_maximum_daily_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='time',
            field=models.TimeField(),
        ),
    ]
