# Generated by Django 5.0.4 on 2024-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_alter_reserves_date_alter_reserves_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studios',
            name='add_stamp',
            field=models.DateTimeField(),
        ),
    ]
