# Generated by Django 5.0.4 on 2024-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0014_alter_studios_add_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studios',
            name='add_stamp',
            field=models.DateTimeField(default='2024-05-03 02:58 PM'),
        ),
    ]
