# Generated by Django 5.0.4 on 2024-05-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0015_alter_studios_add_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studios',
            name='add_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
