# Generated by Django 5.0.4 on 2024-05-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0017_alter_studios_add_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserves',
            old_name='user',
            new_name='customer',
        ),
    ]
