# Generated by Django 5.0.4 on 2024-05-03 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0018_rename_user_reserves_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserves',
            name='add_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 19, 5, 53, 217424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='reserves',
            name='cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studios',
            name='add_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 19, 5, 53, 201792, tzinfo=datetime.timezone.utc)),
        ),
    ]
