# Generated by Django 5.0.4 on 2024-05-03 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0019_reserves_add_stamp_reserves_cancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserves',
            old_name='date',
            new_name='from_date',
        ),
        migrations.RemoveField(
            model_name='reserves',
            name='time',
        ),
        migrations.AddField(
            model_name='reserves',
            name='to_date',
            field=models.DateField(default='2024-05-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserves',
            name='add_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 1, 25, 0, 167416, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studios',
            name='add_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 1, 25, 0, 151792, tzinfo=datetime.timezone.utc)),
        ),
    ]
